spring.datasource.url=jdbc:postgresql://localhost:5432/finpilot?TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=finpilot123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.application.name=finpilot-backend
spring.jpa.open-in-view=false

jwt.secret=finpilot-super-secret-key-that-is-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

server.servlet.context-path=/api